apiVersion: apps/v1
kind: Deployment
metadata:
  name: unicorn-docker-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: unicorn-docker-demo
  template:
    metadata:
      labels:
        app: unicorn-docker-demo
    spec:
      containers:
        - name: springboot
          image: kubernet8s/demo-microservice:unicorn-docker-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: unicorn-docker-demo
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: unicorn-docker-demo
